# MONITOR

monitor=,1920x1080@144,auto,1

################
### PROGRAMS ###
################

$mainMod = SUPER
$terminal = foot
$fileManager = foot yazi
$menu = rofi -show drun
$browser = firefox 
#################
### AUTOSTART ###
#################

exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland

env = QT_QPA_PLATFORMTHEME,qt6ct
env = XCURSOR_THEME,Bibata-Modern-Ice
env = XCURSOR_SIZE,24

#exec-once = hypridle
exec-once = mako
exec-once = clipman restore
exec-once = pamixer --restore-mute
exec-once = waybar
exec-once = hyprpaper


exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = wl-clip-persist --clipboard regular
#############
### INPUT ###
#############
cursor {
    inactive_timeout = 3
    no_hardware_cursors = true
}

input {
    kb_layout = us,ru
    kb_options = grp:win_space_toggle
    follow_mouse = 1

    sensitivity = -0.1
    accel_profile = flat

    touchpad {
        natural_scroll = true
    }
    tablet {
        output = eDP-1
        transform = 0
    }

}


###################
### LOOK & FEEL ###
###################

general {
    gaps_in = 3
    gaps_out = 5
    border_size = 2

    col.active_border = rgba(ffffffff)
    col.inactive_border = rgba(888888ff)

    resize_on_border = true

    layout = dwindle
}


decoration {
    rounding = 10 
    blur {
        enabled = true
        size = 3
        passes = 1
    }

    shadow {
        enabled = true
        range = 4
    }
}
 
# animations {
#     enabled = true

#     bezier = superViteză, 0.05, 0.9, 0.1, 1.05
#     bezier = cyberpunk, 0.05, 0.9, 0.1, 1.1
#     animation = windowsIn, 1, 3, cyberpunk, popin 80%

#     animation = fade, 1, 5, default
#     animation = border, 1, 3, default

#     animation = windowsOut, 1, 3, default, popin 85%
#     animation = windowsMove, 1, 3, superViteză
# }
animations {
    enabled = yes

    bezier = myBezier, 0.05, 0.9, 0.1, 1.05
    bezier = easeOutQuint, 0.22, 1, 0.36, 1
    
    animation = windows, 1, 4, easeOutQuint, popin 85%
    animation = windowsOut, 1, 4, easeOutQuint, popin 85%
    animation = border, 1, 5, default
    animation = borderangle, 1, 5, default
    animation = fade, 1, 4, default
    
    animation = workspaces, 1, 6, default
}



dwindle {
    preserve_split = true
}
################
### KEYBINDS ###
################

# Удалите прошлые правила для floating:1 и вставьте эту строку:
bind = SUPER, R, exec, hyprctl dispatch togglefloating && hyprctl dispatch resizeactive exact 1100 800 && hyprctl dispatch centerwindow
bind = SUPER, S, exec, grim -g "$(slurp)" - | wl-copy -t image/png



bind = $mainMod, W, exec, $terminal
bind = $mainMod, Q, killactive
bind = $mainMod, E, exec, $fileManager
bind = $mainMod, D, exec, $menu
bind = $mainMod, B, exec, $browser
bind = $mainMod, F, fullscreen
bind = $mainMod, M, exit

bind = SUPER, V, exec, cliphist list | rofi -dmenu -display-columns 2 | cliphist decode | wl-copy && wtype -M ctrl -k v -m ctrl

bind = $mainMod, left, movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, up, movefocus, u
bind = $mainMod, down, movefocus, d

# redimensionare ferestre
bind = $mainMod SHIFT, left, resizeactive, -50 0
bind = $mainMod SHIFT, right, resizeactive, 50 0
bind = $mainMod SHIFT, up, resizeactive, 0 -50
bind = $mainMod SHIFT, down, resizeactive, 0 50

# workspace
bind = $mainMod,1,workspace,1
bind = $mainMod,2,workspace,2
bind = $mainMod,3,workspace,3
bind = $mainMod,4,workspace,4
bind = $mainMod,5,workspace,5

# mouse move / resize
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow
